---
name: VyOS Modular - Rolling

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *
  push:
    branches:
      - main
      - dev

jobs:
  build-only:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      #  with:
      #    limit-access-to-actor: true
      #    limit-access-to-users: ramblurr

      - name: Build
        run: make build

  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      # Need permission to write to the Releases tab now.
      # https://github.com/ncipollo/release-action/issues/208.
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Read name
        uses: mikefarah/yq@master
        id: build_name
        with:
          cmd: yq '.name' 'config.yml'

      - name: Read branch
        uses: mikefarah/yq@master
        id: build_branch
        with:
          cmd: yq '.vyos_branch' 'config.yml'

      - name: Setup variables
        id: vars
        run: |
          build_date=$(date +%Y%m%d%H%M)
          echo "tag-name=${{ steps.build_name.outputs.result }}-${build_date}" >> "$GITHUB_OUTPUT"
          echo "iso-name=vyos-${{ steps.build_name.outputs.result }}-${{ steps.build_branch.outputs.result }}-${build_date}-amd64.iso" >> "$GITHUB_OUTPUT"
          echo "build-output=vyos-${{ steps.build_name.outputs.result }}-current-amd64.iso" >> "$GITHUB_OUTPUT"

      - name: Debug
        run: |
          echo "${{ steps.vars.outputs.tag-name }}"
          echo "${{ steps.vars.outputs.iso-name }}"
          echo "${{ steps.vars.outputs.build-output }}"

      - name: Build
        run: make build

      - name: Debug packages
        run: find build/vyos-build/packages

      - name: Rename iso
        run: |
          mv bin/${{ steps.vars.outputs.build-output }} bin/${{ steps.vars.outputs.iso-name }}

      - name: Create release with artifact
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1
        with:
          #token: "${{ steps.generate-token.outputs.token }}"
          tag: "vyos-${{ steps.vars.outputs.tag-name }}"
          artifacts: "bin/${{ steps.vars.outputs.iso-name }}"
          artifactErrorsFailBuild: true
          body: |
            Official VyOS Changelog:
            https://docs.vyos.io/en/latest/changelog/1.4.html
