---
name: VyOS Modular - Rolling

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *
  push:
    branches:
      - main
      - dev

env:
  BUILD_NAME: rmblr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      #  with:
      #    limit-access-to-actor: true
      #    limit-access-to-users: ramblurr

      - name: Build
        run: make build

      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: "./bin/**/*.iso"
          if-no-files-found: error

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      # Need permission to write to the Releases tab now.
      # https://github.com/ncipollo/release-action/issues/208.
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: "bin"

      - name: Setup variables
        run: |
          ls
          ls bin/
          ls bin/*

      - name: Setup variables
        id: vars
        run: |
          build_date=$(date +%Y%m%d%H%M)
          echo "tag-name=${{ env.BUILD_NAME }}-${build_date}" >> "$GITHUB_OUTPUT"
          echo "iso-name=vyos-${{ env.BUILD_NAME }}-current-amd64.iso" >> "$GITHUB_OUTPUT"

      - name: Create release with artifact
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1
        with:
          #token: "${{ steps.generate-token.outputs.token }}"
          tag: "vyos-${{ steps.vars.outputs.tag-name }}"
          artifacts: "bin/${{ steps.vars.outputs.iso-name }}"
          artifactErrorsFailBuild: true
          body: |
            Official VyOS Changelog:
            https://docs.vyos.io/en/latest/changelog/1.4.html
